int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int get_sqrt(int i, int j);
int is_it_prime(int n, int j);
int is_palindrome(char *s);
int is_it_pali(char *s, int len, int index);
int str_len(char *s, int l);
int wildcmp(char *s1, char *s2);
